version: '3'
services:
#   traefik:
#     image: traefik:v2.2
#     command: 
#       - --entrypoints.web.address=:80
#       - --providers.docker=true
#       - --api.insecure 
#     ports:
#         - "8082:80"
#         - "8081:8080"
#         - "445:443"
#     volumes:
#         - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: .
    # labels:
    #     - "traefik.frontend.rule=Host:test00501.yegobox.com"
    ports:
      - "8083:8080"
    domainname: test00501.yegobox.com
    hostname: test00501.yegobox.com
    # volumes:
    #   - .:/usr/src/app
    # environment:
    #   FLASK_ENV: development
#   redis:
#     image: "redis:alpine"