version: '3'
services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
        - "8082:80"
        - "8081:8080"
        - "445:443"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /dev/null:/traefik.toml 
  web:
    build: .
    labels:
        - "traefik.backend=box-be"
        - "traefik.frontend.rule=Host:test00501.yegobox.com"
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    # environment:
    #   FLASK_ENV: development
  redis:
    image: "redis:alpine"